version: '2'

services:
  svc-salary:
    image: jmurihub/seicentosalary:2.0.2
    container_name: salary

    environment:
      - APP_STAGE=TEST
      - DB_URL_TEST=jdbc:sqlserver:[SERVER]:1433;database=[DBNAME];encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
      - DB_USR_TEST=[DBUSER]
      - DB_PWD_TEST=[DBPASSWORD]
      - tenantid=[Company.com]
      - clientid=[Azure ClientID]
      - clientkey=[Azure Client Key]
      
    ports:
      - 8080:8080
    networks:
      - docker-network

    restart: unless-stopped

networks:
  docker-network:
    driver: bridge
    